include:
  - board: nice_nano_v2
    shield: cosmos_left
  - board: nice_nano_v2
    shield: cosmos_right
  - board: nice_nano_v2
    shield: cosmos_central
  - board: nice_nano_v2
    shield: settings_reset