include:
  - board: nice_nano_v2
    shield: cosmos_3p_left
  - board: nice_nano_v2
    shield: cosmos_3p_right
  - board: nice_nano_v2
    shield: cosmos_3p_central
  - board: nice_nano_v2
    shield: settings_reset